export const FETCH_EARPHONE_REQUEST = 'FETCH_EARPHONE_REQUEST';
export const FETCH_EARPHONE_SUCCESS = 'FETCH_EARPHONE_SUCCESS';
export const FETCH_EARPHONE_FAILURE = 'FETCH_EARPHONE_FAILURE';


export const FETCH_EARPHONE_CATEGORY_REQUEST = 'FETCH_EARPHONE_CATEGORY_REQUEST';
export const FETCH_EARPHONE_CATEGORY_SUCCESS = 'FETCH_EARPHONE_CATEGORY_SUCCESS';
export const FETCH_EARPHONE_CATEGORY_FAILURE = 'FETCH_EARPHONE_CATEGORY_FAILURE';

