export const FETCH_HEADPHONES_REQUEST = 'FETCH_HEADPHONES_REQUEST';
export const FETCH_HEADPHONES_SUCCESS = 'FETCH_HEADPHONES_SUCCESS';
export const FETCH_HEADPHONES_FAILURE = 'FETCH_HEADPHONES_FAILURE';